import { Projeto, SuggestionIdea, SazonalItem, Channel, UserProfile, DebateProjeto } from '../types';

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'user-1',
    nome: 'Mariana Silva',
    email: 'mariana.silva@inovatti.com.br',
    cargo: 'Copywriter & Estrategista',
    avatar: 'MS',
    cor: 'from-pink-500 to-rose-600',
    votosRealizados: 14
  },
  {
    id: 'user-2',
    nome: 'Carlos Souza',
    email: 'carlos.souza@inovatti.com.br',
    cargo: 'Designer Gráfico & Visual',
    avatar: 'CS',
    cor: 'from-violet-500 to-purple-600',
    votosRealizados: 11
  },
  {
    id: 'user-3',
    nome: 'Rafael Mello',
    email: 'rafael.mello@inovatti.com.br',
    cargo: 'Gestor de Tráfego & SEO',
    avatar: 'RM',
    cor: 'from-blue-500 to-indigo-600',
    votosRealizados: 16
  },
  {
    id: 'user-4',
    nome: 'Beatriz Costa',
    email: 'beatriz.costa@inovatti.com.br',
    cargo: 'Videomaker & Social Media',
    avatar: 'BC',
    cor: 'from-amber-500 to-orange-600',
    votosRealizados: 12
  },
  {
    id: 'user-5',
    nome: 'Lucas Fontes',
    email: 'lucas.fontes@inovatti.com.br',
    cargo: 'Coordenador Geral & Head',
    avatar: 'LF',
    cor: 'from-emerald-500 to-teal-600',
    votosRealizados: 18
  }
];

export const TEAM_MEMBERS = INITIAL_USERS.map(u => ({
  nome: u.nome,
  cargo: u.cargo,
  email: u.email
}));

export const CHANNELS: Channel[] = [
  'Instagram',
  'Blog',
  'Google',
  'YouTube',
  'LinkedIn',
  'TikTok',
  'E-mail Marketing'
];

export const INITIAL_PAUTAS: Projeto[] = [
  {
    id: 'p-101',
    titulo: 'Campanha Outubro Rosa: Cuidados e Bem-Estar no Lar',
    canal: 'Instagram',
    responsavel: 'Mariana Silva',
    email: 'mariana.silva@inovatti.com.br',
    status: 'Publicado',
    dataPublicacao: '2026-10-02',
    dataLimiteProducao: '2026-09-30',
    ctaObjetivo: 'Conscientização e engajamento humanizado',
    observacoes: 'Post carrossel humanizado valorizando qualidade de vida nas casas em condomínio de Maricá.',
    alertaEnviado: false,
  },
  {
    id: 'p-102',
    titulo: 'Tour Virtual: Mansão em Itaipuaçu com Vista Mar',
    canal: 'YouTube',
    responsavel: 'Beatriz Costa',
    email: 'beatriz.costa@inovatti.com.br',
    status: 'Publicado',
    dataPublicacao: '2026-10-06',
    dataLimiteProducao: '2026-10-04',
    ctaObjetivo: 'Agendar visita com corretor via WhatsApp',
    observacoes: 'Vídeo completo gravado com drone na orla revitalizada de Itaipuaçu.',
    alertaEnviado: false,
  },
  {
    id: 'p-103',
    titulo: 'Artigo SEO: Por que investir em terrenos residenciais em Maricá em 2026?',
    canal: 'Blog',
    responsavel: 'Mariana Silva',
    email: 'mariana.silva@inovatti.com.br',
    status: 'Publicado',
    dataPublicacao: '2026-10-09',
    dataLimiteProducao: '2026-10-07',
    ctaObjetivo: 'Download do Guia de Loteamentos',
    observacoes: 'Foco no impacto das obras viárias, tarifa zero e crescimento comercial da cidade.',
    alertaEnviado: false,
  },
  {
    id: 'p-104',
    titulo: 'Infográfico: Custos de Escritura, ITBI e RGI no Estado do RJ',
    canal: 'Instagram',
    responsavel: 'Carlos Souza',
    email: 'carlos.souza@inovatti.com.br',
    status: 'Em produção',
    dataPublicacao: '2026-10-15',
    dataLimiteProducao: '2026-10-13',
    ctaObjetivo: 'Salvar o post para consulta rápida',
    observacoes: 'Visual didático para clientes com dúvidas na fase final da aquisição imobiliária.',
    alertaEnviado: false,
  },
  {
    id: 'p-105',
    titulo: 'Guia de Locação para Temporada de Verão (Ponta Negra & Itaipuaçu)',
    canal: 'Blog',
    responsavel: 'Mariana Silva',
    email: 'mariana.silva@inovatti.com.br',
    status: 'Em produção',
    dataPublicacao: '2026-10-20',
    dataLimiteProducao: '2026-10-18',
    ctaObjetivo: 'Cadastrar imóvel para temporada',
    observacoes: 'Preparação antecipada para proprietários maximizarem rendimento de aluguéis de verão.',
    alertaEnviado: false,
  },
  {
    id: 'p-106',
    titulo: 'Depoimento em Vídeo: "Realizamos nosso sonho no Condomínio Pedra Verde"',
    canal: 'Instagram',
    responsavel: 'Beatriz Costa',
    email: 'beatriz.costa@inovatti.com.br',
    status: 'Em produção',
    dataPublicacao: '2026-10-23',
    dataLimiteProducao: '2026-10-21',
    ctaObjetivo: 'Prova social e envio de direct',
    observacoes: 'Reels de 45 segundos com família recém-mudada da capital para Maricá.',
    alertaEnviado: false,
  },
  {
    id: 'p-107',
    titulo: 'Anúncio Google Ads: Feirão Digital de Sobrados em Inoã e São José',
    canal: 'Google',
    responsavel: 'Rafael Mello',
    email: 'rafael.mello@inovatti.com.br',
    status: 'Revisão',
    dataPublicacao: '2026-10-27',
    dataLimiteProducao: '2026-10-25',
    ctaObjetivo: 'Conversão para formulário de simulação de financiamento',
    observacoes: 'Copy orientada a conversão para leads qualificados de Niterói e São Gonçalo.',
    alertaEnviado: false,
  },
  {
    id: 'p-108',
    titulo: 'Aquecimento Black Friday Imobiliária: Condições Exclusivas de Lançamento',
    canal: 'Instagram',
    responsavel: 'Carlos Souza',
    email: 'carlos.souza@inovatti.com.br',
    status: 'Ideia',
    dataPublicacao: '2026-10-10',
    dataLimiteProducao: '2026-10-08',
    ctaObjetivo: 'Entrar na lista VIP do Feirão Black Friday',
    observacoes: 'Faltam menos de 24h para a Data Limite de Produção e o status ainda é "Ideia"!',
    alertaEnviado: true,
    dataAlerta: '2026-10-07 07:15',
  },
  {
    id: 'p-109',
    titulo: 'Especial Dia do Corretor de Imóveis: Homenagem e Bastidores Inovatti',
    canal: 'Instagram',
    responsavel: 'Mariana Silva',
    email: 'mariana.silva@inovatti.com.br',
    status: 'Ideia',
    dataPublicacao: '2026-10-11',
    dataLimiteProducao: '2026-10-08',
    ctaObjetivo: 'Valorização da equipe e comentários com depoimentos',
    observacoes: 'Projeto comemorativo estratégico com menos de 24h de prazo e status "Ideia". Alerta disparado.',
    alertaEnviado: true,
    dataAlerta: '2026-10-07 07:15',
  }
];

export const INITIAL_IDEAS: SuggestionIdea[] = [
  {
    id: 'idea-201',
    titulo: 'Guia definitivo de financiamento para primeiro imóvel (MCMV e SBPE)',
    canal: 'Blog',
    responsavel: 'Mariana Silva',
    sugeridoPor: 'Gestor Comercial Inovatti',
    briefing: 'Muitos compradores de Maricá têm dúvidas sobre entrada facilitada, subsídio e uso do FGTS na compra da casa própria.',
    ctaObjetivo: 'Baixar calculadora de financiamento gratuita',
    dataCriacao: '2026-10-05',
  },
  {
    id: 'idea-202',
    titulo: 'Carrossel: As 5 melhores praias e lagoas de Maricá para viver com a família',
    canal: 'Instagram',
    responsavel: 'Carlos Souza',
    sugeridoPor: 'Equipe de Marketing',
    briefing: 'Destacar Barra de Maricá, Cordeirinho, Ponta Negra, Lagoa de Araçatiba e a tranquilidade de quem busca refúgio fora da capital.',
    ctaObjetivo: 'Comentar qual bairro você prefere para morar',
    dataCriacao: '2026-10-06',
  },
  {
    id: 'idea-203',
    titulo: 'FAQ Jurídico: O que checar na documentação antes de assinar a promessa de compra e venda?',
    canal: 'Google',
    responsavel: 'Rafael Mello',
    sugeridoPor: 'Jurídico Inovatti',
    briefing: 'Projeto educativo de alta autoridade para gerar credibilidade e captura de leads de compradores de alto padrão e condomínios.',
    ctaObjetivo: 'Falar com nosso consultor jurídico sem compromisso',
    dataCriacao: '2026-10-06',
  },
];

export const INITIAL_DEBATE_PAUTAS: DebateProjeto[] = [
  {
    id: 'deb-1',
    titulo: 'Websérie com Drone: "Do Aluguel em Niterói à Mansão Linear com Piscina em Maricá"',
    autorNome: 'Mariana Silva',
    autorEmail: 'mariana.silva@inovatti.com.br',
    autorRole: 'Copywriter & Estrategista',
    canal: 'YouTube',
    briefing: 'Formato cinematográfico de mini-documentário em 3 episódios gravados em 4K acompanhando a mudança de uma família de Icaraí para um condomínio fechado em Inoã, com captações aéreas e depoimentos emotivos.',
    ctaObjetivo: 'Link na descrição para simular financiamento sem compromisso',
    dataCriacao: '06/10/2026 14:30',
    statusDebate: 'em_votacao',
    votosAprovar: ['user-1', 'user-3', 'user-4', 'user-5'], // 4 votos a favor! (Maioria da equipe quer!)
    votosRevisar: ['user-2'],
    votosRejeitar: [],
    pareceresViabilidade: [
      {
        id: 'viab-1',
        projetoId: 'deb-1',
        userId: 'user-4',
        userName: 'Beatriz Costa',
        userRole: 'Videomaker & Social Media',
        userColor: 'from-amber-500 to-orange-600',
        status: 'inviavel',
        justificativa: 'INVIABILIDADE TÉCNICA E OPERACIONAL: A ideia é excelente, mas nossa agenda de captação de drone já está 100% comprometida este mês com as entregas de Itaipuaçu. Além disso, a lente anamórfica e câmera 4K estão na assistência técnica até o dia 28. Sem orçamento para terceirizar equipe de vídeo externa (estimado em R$ 1.500), é humanamente impossível produzir com o padrão exigido antes do mês que vem.',
        recursosNecessarios: 'Contratação de videomaker freelancer com drone próprio ou adiamento da gravação para Novembro',
        timestamp: '06/10 16:15'
      },
      {
        id: 'viab-2',
        projetoId: 'deb-1',
        userId: 'user-3',
        userName: 'Rafael Mello',
        userRole: 'Gestor de Tráfego & SEO',
        userColor: 'from-blue-500 to-indigo-600',
        status: 'ressalva',
        justificativa: 'Viável apenas se tivermos verba de tráfego de pelo menos R$ 800 para impulsionar os episódios completos no YouTube. Sem distribuição paga, o retorno sobre o alto esforço de gravação será baixo.',
        recursosNecessarios: 'Verba dedicada de R$ 800 no Google Ads',
        timestamp: '06/10 17:00'
      }
    ],
    comments: [
      {
        id: 'c-1',
        projetoId: 'deb-1',
        userId: 'user-3',
        userName: 'Rafael Mello',
        userRole: 'Gestor de Tráfego',
        userCor: 'from-blue-500 to-indigo-600',
        content: 'O tema é um tiro certeiro de audiência, mas o parecer da Beatriz foi muito claro sobre a sobrecarga de gravações.',
        timestamp: '06/10 17:10'
      },
      {
        id: 'c-2',
        projetoId: 'deb-1',
        userId: 'user-5',
        userName: 'Lucas Fontes',
        userRole: 'Coordenador Geral',
        userCor: 'from-emerald-500 to-teal-600',
        content: 'Como Coordenador Geral, concordo com a regra: mesmo com a maioria dos votos a favor, o parecer técnico da Beatriz bloqueia a ida para o calendário até ajustarmos o escopo ou alocarmos verba de produção.',
        timestamp: '07/10 08:30'
      }
    ]
  },
  {
    id: 'deb-2',
    titulo: 'Campanha de Captação: "Seu Imóvel em Maricá Vendido em até 60 Dias ou Consultoria Grátis"',
    autorNome: 'Carlos Souza',
    autorEmail: 'carlos.souza@inovatti.com.br',
    autorRole: 'Designer Gráfico & Visual',
    canal: 'Instagram',
    briefing: 'Carrossel de autoridade voltado para proprietários que estão com imóveis estagnados em placas de rua. Apresentar os 4 pilares do Método Inovatti: fotografia HDR, tour com drone, qualificação financeira do comprador e tráfego pago geolocalizado.',
    ctaObjetivo: 'Enviar direct com a palavra EXCLUSIVIDADE para agendamento de visita técnica',
    dataCriacao: '05/10/2026 11:20',
    statusDebate: 'consensuado',
    votosAprovar: ['user-1', 'user-2', 'user-3', 'user-4', 'user-5'],
    votosRevisar: [],
    votosRejeitar: [],
    promovidaParaCalendario: false,
    pareceresViabilidade: [
      {
        id: 'viab-3',
        projetoId: 'deb-2',
        userId: 'user-2',
        userName: 'Carlos Souza',
        userRole: 'Designer Gráfico & Visual',
        userColor: 'from-violet-500 to-purple-600',
        status: 'viavel',
        justificativa: '100% VIÁVEL: Os templates de layout já estão finalizados no Figma. Produção estimada em menos de 3 horas de design.',
        recursosNecessarios: 'Apenas aprovação final do texto com o corretor responsável',
        timestamp: '05/10 14:00'
      },
      {
        id: 'viab-4',
        projetoId: 'deb-2',
        userId: 'user-3',
        userName: 'Rafael Mello',
        userRole: 'Gestor de Tráfego & SEO',
        userColor: 'from-blue-500 to-indigo-600',
        status: 'viavel',
        justificativa: 'Viável: Campanha de tráfego já configurada no Meta Ads para o público de proprietários locais de Maricá.',
        recursosNecessarios: 'Nenhum recurso extra necessário',
        timestamp: '05/10 14:30'
      }
    ],
    comments: [
      {
        id: 'c-4',
        projetoId: 'deb-2',
        userId: 'user-5',
        userName: 'Lucas Fontes',
        userRole: 'Coordenador Geral',
        userCor: 'from-emerald-500 to-teal-600',
        content: 'Consenso total de votos E viabilidade técnica 100% verde! Projeto liberado para o Coordenador promover.',
        timestamp: '06/10 09:15'
      }
    ]
  },
  {
    id: 'deb-3',
    titulo: 'Reels Comparativo: "O que R$ 600 mil Compram em Niterói vs Casa Linear em Itaipuaçu"',
    autorNome: 'Beatriz Costa',
    autorEmail: 'beatriz.costa@inovatti.com.br',
    autorRole: 'Videomaker & Social Media',
    canal: 'Instagram',
    briefing: 'Vídeo dinâmico de 45 segundos usando formato de tela dividida ou comparativo rápido mostrando o que R$ 600 mil compram em Icaraí (apartamento antigo sem vaga) vs casa linear com piscina, 3 quartos e energia solar na praia de Itaipuaçu.',
    ctaObjetivo: 'Comente "COMPARAR" para ver a ficha completa com endereço e fotos',
    dataCriacao: '07/10/2026 07:50',
    statusDebate: 'em_votacao',
    votosAprovar: ['user-1', 'user-4'],
    votosRevisar: ['user-3'],
    votosRejeitar: [],
    pareceresViabilidade: [
      {
        id: 'viab-5',
        projetoId: 'deb-3',
        userId: 'user-4',
        userName: 'Beatriz Costa',
        userRole: 'Videomaker & Social Media',
        userColor: 'from-amber-500 to-orange-600',
        status: 'viavel',
        justificativa: 'Totalmente viável: Gravação rápida com celular em estabilizador durante visita de rotina a imóvel já liberado pelo proprietário.',
        recursosNecessarios: 'Gimbal para smartphone e microfone sem fio de lapela',
        timestamp: '07/10 08:15'
      }
    ],
    comments: [
      {
        id: 'c-6',
        projetoId: 'deb-3',
        userId: 'user-3',
        userName: 'Rafael Mello',
        userRole: 'Gestor de Tráfego',
        userCor: 'from-blue-500 to-indigo-600',
        content: 'Aprovado na viabilidade, apenas precisamos cuidar da copy para valorizar Maricá sem ofender os moradores da cidade vizinha.',
        timestamp: '07/10 08:35'
      }
    ]
  }
];

export const SAZONAL_DATABASE: SazonalItem[] = [
  {
    id: 'saz-1',
    nome: 'Sazonalidade de Verão (Locação de Temporada)',
    dataStr: 'Janeiro / Fevereiro',
    mes: 1,
    trimestre: 'Jan-Mar',
    nicho: 'Locação e Investimento Turístico',
    contexto: 'Pico de procura por casas com piscina em Itaipuaçu e Ponta Negra para veraneio. Momento ideal para proprietários anunciarem e locatários garantirem reservas com antecedência.',
    tituloSugerido: 'Verão em Maricá: Como rentabilizar seu imóvel na alta temporada de locação',
    canalRecomendado: 'Blog',
  },
  {
    id: 'saz-2',
    nome: 'Dia do Consumidor',
    dataStr: '15 de Março',
    mes: 3,
    trimestre: 'Jan-Mar',
    nicho: 'Direitos do Comprador e Transparência',
    contexto: 'Oportunidade para reforçar a transparência dos contratos, segurança jurídica na compra e atendimento consultivo da Imobiliária Inovatti.',
    tituloSugerido: 'Dia do Consumidor: Garantias e direitos fundamentais ao comprar seu imóvel em Maricá',
    canalRecomendado: 'Instagram',
  },
  {
    id: 'saz-3',
    nome: 'Feirão de Financiamento da Caixa & Bancos',
    dataStr: 'Abril a Junho',
    mes: 4,
    trimestre: 'Abr-Jun',
    nicho: 'Financiamento Bancário (Caixa / Bradesco / Itaú)',
    contexto: 'Período tradicional de feirões imobiliários. Compradores aproveitam liberação de crédito do primeiro semestre para buscar sobrados e condomínios fechados.',
    tituloSugerido: 'Feirão de Financiamento: Passo a passo para aprovar seu crédito imobiliário na hora',
    canalRecomendado: 'Google',
  },
  {
    id: 'saz-4',
    nome: 'Dia das Mães',
    dataStr: '2º Domingo de Maio',
    mes: 5,
    trimestre: 'Abr-Jun',
    nicho: 'Emocional / Lar e Conforto Familiar',
    contexto: 'Apelo afetivo forte ligado à realização de conquistar a casa espaçosa com quintal que as mães e famílias sempre sonharam.',
    tituloSugerido: 'O presente do lar próprio: Histórias de mães que conquistaram seu cantinho em Maricá',
    canalRecomendado: 'Instagram',
  },
  {
    id: 'saz-5',
    nome: 'Aniversário de Maricá',
    dataStr: '26 de Maio',
    mes: 5,
    trimestre: 'Abr-Jun',
    nicho: 'Hiperlocal / Valorização Urbana e Qualidade de Vida',
    contexto: 'Celebração da cidade! Oportunidade para destacar o transporte gratuito Vermelhinho, polo universitário, orlas revitalizadas e valorização imobiliária recorde.',
    tituloSugerido: '26 de Maio: Por que Maricá se tornou a cidade mais acolhedora e promissora do RJ',
    canalRecomendado: 'YouTube',
  },
  {
    id: 'saz-6',
    nome: 'Dia dos Namorados',
    dataStr: '12 de Junho',
    mes: 6,
    trimestre: 'Abr-Jun',
    nicho: 'Casais Jovens / Primeiro Imóvel',
    contexto: 'Casais planejando casamento e o início da vida a dois. Foco em casas lineares compactas ou sobrados com parcelas que cabem no orçamento conjunto.',
    tituloSugerido: 'Construindo o futuro juntos: O plano ideal para casais comprarem o primeiro imóvel em Maricá',
    canalRecomendado: 'Instagram',
  },
  {
    id: 'saz-7',
    nome: 'Dia do Corretor de Imóveis',
    dataStr: '27 de Agosto',
    mes: 8,
    trimestre: 'Jul-Set',
    nicho: 'Autoridade Institucional e Valorização Profissional',
    contexto: 'Data máxima do segmento. Humaniza os corretores locais de Maricá, reforçando ética profissional, conhecimento das regiões e assessoria de ponta a ponta sem dor de cabeça.',
    tituloSugerido: 'Dia do Corretor de Imóveis: A consultoria experiente que transforma buscas em lares seguros',
    canalRecomendado: 'Instagram',
  },
  {
    id: 'saz-8',
    nome: 'Dia do Cliente',
    dataStr: '15 de Setembro',
    mes: 9,
    trimestre: 'Jul-Set',
    nicho: 'Fidelização e Condições Especiais',
    contexto: 'Celebração das famílias atendidas pela Inovatti, com distribuição de depoimentos, isenção em taxas de avaliação ou bônus de escritura para novos contratos.',
    tituloSugerido: 'Dia do Cliente Inovatti: Homenagem às famílias que confiaram em nós para realizar o sonho da moradia',
    canalRecomendado: 'E-mail Marketing',
  },
  {
    id: 'saz-9',
    nome: 'Outubro Rosa',
    dataStr: 'Mês de Outubro',
    mes: 10,
    trimestre: 'Out-Dez',
    nicho: 'Conscientização Social & Saúde',
    contexto: 'Engajamento com causas humanizadas, ambiente de trabalho saudável e valorização da vida, gerando conexão genuína com a comunidade maricaense.',
    tituloSugerido: 'Outubro Rosa Inovatti: Cuidar de você é o primeiro passo para planejar todos os seus sonhos',
    canalRecomendado: 'Instagram',
  },
  {
    id: 'saz-10',
    nome: 'Novembro Azul',
    dataStr: 'Mês de Novembro',
    mes: 11,
    trimestre: 'Out-Dez',
    nicho: 'Saúde Masculina e Prevenção',
    contexto: 'Comunicação preventiva e bem-estar do homem, associando a tranquilidade de quem cuida da saúde para desfrutar o patrimônio conquistado.',
    tituloSugerido: 'Novembro Azul: Prevenção e cuidado com a saúde para quem cuida do futuro da família',
    canalRecomendado: 'Instagram',
  },
  {
    id: 'saz-11',
    nome: 'Black Friday Imobiliária',
    dataStr: 'Última Sexta de Novembro',
    mes: 11,
    trimestre: 'Out-Dez',
    nicho: 'Vendas Agressivas e Descontos Reais',
    contexto: 'Proprietários e construtoras reduzem margens para fechar o ano. Época de maior tráfego de pessoas decididas a investir antes da virada do calendário.',
    tituloSugerido: 'Black Friday Inovatti: Sobrados e terrenos em Maricá com condições exclusivas e entrada facilitada',
    canalRecomendado: 'Google',
  },
  {
    id: 'saz-12',
    nome: 'Natal em Família',
    dataStr: '25 de Dezembro',
    mes: 12,
    trimestre: 'Out-Dez',
    nicho: 'Celebração em Família e Conquista',
    contexto: 'Visual acolhedor, casas com espaço gourmet e varanda para reunir familiares. Clima de celebração do fechamento de ciclos e novos recomeços.',
    tituloSugerido: 'Natal de casa nova: O orgulho de reunir quem você ama sob o seu próprio teto em Maricá',
    canalRecomendado: 'Instagram',
  },
  {
    id: 'saz-13',
    nome: 'Réveillon & Metas de Ano Novo',
    dataStr: '31 de Dezembro',
    mes: 12,
    trimestre: 'Out-Dez',
    nicho: 'Metas de Novo Ciclo e Qualidade de Vida',
    contexto: 'Momento chave em que famílias da capital e Grande Rio decidem mudar de vida e trocar o estresse pela tranquilidade e segurança de Maricá no ano que chega.',
    tituloSugerido: 'Ano Novo, Vida Nova: Por que 2027 é o ano perfeito para viver com qualidade de vida em Maricá',
    canalRecomendado: 'Blog',
  }
];
